
  BASE_API_URL = "x"
  DBMS_DEFAULT_DATABASE = "x"
  API_VERSION = "x"
  REVALIDATE_DATA_INTERVAL = "y"
  READONLY_USER = "z"
  SITE_DEFAULT_TITLE = "d"
  GA_TRACKING_ID = ""
  PROOFMARKET_TOOLCHAIN_REPO = "d"
  CIRCUIT_DEVELOPER_GUIDE_URL = "wed"
  API_RESPONSE_WAIT_TIMEOUT = "fefwe"
  OTEL_TRACE_EXPORTER_URL = "de"
  OTEL_SERVICE_NAME = "wefefe"

